[project]
name = "apex-exercise-2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13, <3.14"
dependencies = [
    "datasets>=4.5.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.9",
    "openai>=1.0.0",
    "milvus-lite>=2.5.1",
    "pandas>=3.0.0",
    "pymilvus[model]>=2.6.9",
    "python-dotenv>=1.2.1",
    "ragas>=0.4.3",
    "torch>=2.10.0",
    "setuptools>=75.0.0,<76",
    "transformers>=4.40.0,<5",
]
